name: Build File in Master Branch
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - master
jobs:
  build-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: git add .
      - run: git commit -m "index.js build"
      - run: git push origin master
